services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.docker-compose
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  worker:
    build: .
    command: celery -A database.celery_worker worker --loglevel=info
    depends_on:
      - redis
      - db
    networks:
      - mynetwork
    env_file:
      - .env.docker-compose

  db:
    container_name: glowTrack
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: glowTrack
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
